added thshows_ids as a parameter to filter by path/tag
kodi-community-addons/script.module.thetvdb pull request #3
Opened 2017-09-22 13:05 UTC by redglory

Following the change in next episodes which can be filtered by path and tag parameters, I've applied same concept to nextairing and unaired episodes, on script.module.thetvdb module.

2017-09-24 18:30 UTC, marcelveldt requested changes

2017-09-24 18:30 UTC, marcelveldt commented on lib/thetvdb.py
> +    def get_kodi_unaired_episodes(self, single_episode_per_show=True, tvshows_ids=[], include_last_episode=False):
this is a breaking change... This module is also used in other projects.

Please make this additional parameter an optional filter param.
Also it's bad practice to set the default value to an empty array.

Please change the line to this:

def get_kodi_unaired_episodes(self, single_episode_per_show=True, include_last_episode=False, tvshow_ids=None):

2017-09-24 18:30 UTC, marcelveldt commented on lib/thetvdb.py
> +            if kodi_serie["tvshowid"] in tvshows_ids:
In relation to the previous comment, this line should be:

if not tvshow_ids or (tvshow_ids and kodi_serie["tvshowid"] in tvshows_ids):

2017-10-01 12:05 UTC, redglory commented
Fixed tvshows_ids parameter and made it optional. :)

2017-10-02 05:19 UTC, marcelveldt commented
Perfect, thanks !

2017-10-02 05:19 UTC, merged